# SHOW AN IMAGE IN BROWSER UNING webbrowser
# import antigravity


# import webbrowser

# webbrowser.open("https://youtu.be/V9EE2aaUc2Q?si=sjO2uHFumRVHAmd2")

# # webbrowser.open("link")
                

                # text to speech
                # import pyttsx3

# import pyttsx3

# engine = pyttsx3.init()

# engine.say(" hi, today is very cold due to rain")
# engine.runAndWait()

import pyttsx3

speaker = pyttsx3.init()

speaker.say("Hello, santosh nepali, i m your text to speech speaker, nice to meeet you")
speaker.runAndWait()